//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JazzMetricsEntities : DbContext
    {
        public JazzMetricsEntities()
            : base("name=JazzMetricsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<AppError> AppErrors { get; set; }
        public virtual DbSet<Metric> Metrics { get; set; }
        public virtual DbSet<MetricType> MetricTypes { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectMetric> ProjectMetrics { get; set; }
        public virtual DbSet<UserProject> UserProjects { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<AffectedField> AffectedFields { get; set; }
        public virtual DbSet<AspiceProcess> AspiceProcesses { get; set; }
        public virtual DbSet<AspiceVersion> AspiceVersions { get; set; }
        public virtual DbSet<MetricColumn> MetricColumns { get; set; }
        public virtual DbSet<ProjectMetricColumnValue> ProjectMetricColumnValues { get; set; }
        public virtual DbSet<ProjectMetricSnapshot> ProjectMetricSnapshots { get; set; }
    }
}
