//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMetricSnapshot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectMetricSnapshot()
        {
            this.ProjectMetricColumnValues = new HashSet<ProjectMetricColumnValue>();
        }
    
        public int ID { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public int ProjectMetricID { get; set; }
    
        public virtual ProjectMetric ProjectMetric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMetricColumnValue> ProjectMetricColumnValues { get; set; }
    }
}
