//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomError
    {
        public int ID { get; set; }
        public System.DateTime Time { get; set; }
        public string Module { get; set; }
        public string Function { get; set; }
        public string Exception { get; set; }
        public string InnerException { get; set; }
        public string Message { get; set; }
        public bool Solved { get; set; }
        public bool Deleted { get; set; }
        public string User { get; set; }
    }
}
