//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metric()
        {
            this.ProjectMetrics = new HashSet<ProjectMetric>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MetricTypeID { get; set; }
        public string Identificator { get; set; }
        public int AspiceProcessID { get; set; }
        public int AffectedFieldID { get; set; }
    
        public virtual MetricType MetricType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMetric> ProjectMetrics { get; set; }
        public virtual AffectedField AffectedField { get; set; }
        public virtual AspiceProcess AspiceProcess { get; set; }
    }
}
