//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMetricColumnValue
    {
        public int ID { get; set; }
        public decimal Value { get; set; }
        public int ProjectMetricSnapshotID { get; set; }
        public int MetricColumnID { get; set; }
    
        public virtual MetricColumn MetricColumn { get; set; }
        public virtual ProjectMetricSnapshot ProjectMetricSnapshot { get; set; }
    }
}
