//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMetric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectMetric()
        {
            this.ProjectMetricSnapshots = new HashSet<ProjectMetricSnapshot>();
        }
    
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int MetricID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string DataURL { get; set; }
        public bool Warning { get; set; }
        public Nullable<decimal> MinimalWarningValue { get; set; }
        public string DataUsername { get; set; }
        public string DataPassword { get; set; }
    
        public virtual Metric Metric { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMetricSnapshot> ProjectMetricSnapshots { get; set; }
    }
}
