"use strict";
//LOGIN
export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";
export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAILED = "LOGGED_FAILED";
export const LOGIN_SUCCESSFULLY = "LOGGED_SUCCESSFULLY";
export const LOGIN_RESET_CONTROL_VARS = "LOGIN_RESET_CONTROL_VARS";
export const LOGIN_SET_MESSAGE = "LOGIN_SET_MESSAGE";

//HOME
export const HOME_LOAD = "HOME_LOAD";
export const HOME_FAIL = "HOME_FAIL";
export const HOME_RESET_CONTROL_VARS = "HOME_RESET_CONTROL_VARS";
export const HOME_UNAUTHORIZED = "HOME_UNAUTHORIZED";

//STARTUP
export const STARTUP_LOAD = "STARTUP_LOAD";
export const STARTUP_LOAD_DONE = "STARTUP_LOAD_DONE";
export const STARTUP_LOAD_DW_DONE = "STARTUP_LOAD_DW_DONE";
export const STARTUP_LOGOUT = "STARTUP_LOGOUT";

//TEST
export const TEST_LOAD_DONE = "TEST_LOAD_DONE";

//SPINNER
export const SPINNER_START = "SPINNER_START";
export const SPINNER_STOP = "SPINNER_STOP";

//FUNCTION
export const FUNCTION_SET = "FUNCTION_SET";
export const FUNCTION_RESET = "FUNCTION_RESET";

//PARAMETERS
export const PARAMETERS_SELECT = "PARAMETERS_SELECT";
export const PARAMETERS_LOAD = "PARAMETERS_LOAD";
export const PARAMETERS_FAIL = "PARAMETERS_FAIL";
export const PARAMETERS_SET_DATA = "PARAMETERS_SET_DATA";
export const PARAMETERS_RESET_CONTROL_VARS = "PARAMETERS_RESET_CONTROL_VARS";
export const PARAMETERS_UNAUTHORIZED = "PARAMETERS_UNAUTHORIZED";
export const PARAMETERS_RESET_SCAN_DATA = "PARAMETERS_RESET_SCAN_DATA";

//SCAN
export const SCAN_UPLOAD = "SCAN_UPLOAD";
export const SCAN_FAIL = "SCAN_FAIL";
export const SCAN_RESET_CONTROL_VARS = "SCAN_RESET_CONTROL_VARS";
export const SCAN_UNAUTHORIZED = "SCAN_UNAUTHORIZED";
export const SCAN_RESET_SCAN_DATA = "SCAN_RESET_SCAN_DATA";
export const SCAN_RESET_VISUAL_DATA = "SCAN_RESET_VISUAL_DATA";
export const SCAN_RESET_QUESTION = "SCAN_RESET_QUESTION";