/*CREATE DATABASE JazzMetrics;
go*/

USE JazzMetrics;
go

/*USE pri0115;
go*/

CREATE TABLE [Language] (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[ISO639_1Code] NVARCHAR(2) NOT NULL,
	[ISO639_3Code]  NVARCHAR(3) NOT NULL
);

CREATE TABLE [Role] (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL
);

CREATE TABLE [User] (
	ID INTEGER IDENTITY(1,1) PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(256) NOT NULL,
	Salt NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	RoleID INTEGER NOT NULL,
	LanguageID INTEGER NOT NULL,
	CONSTRAINT FK_USER_ROLE FOREIGN KEY (RoleID) REFERENCES [Role](ID),
	CONSTRAINT FK_USER_LANGUAGE FOREIGN KEY (LanguageID) REFERENCES [Language](ID)
);

CREATE TABLE CustomError (
	[ID] INT IDENTITY(1,1) NOT NULL,
	[Time] DATETIME NOT NULL,
	[Module] NVARCHAR(128) NOT NULL,
	[Function] NVARCHAR(128) NOT NULL,
	[Exception] NVARCHAR(MAX) NOT NULL,
	[InnerException] NVARCHAR(MAX) NOT NULL,
	[Message] NVARCHAR(MAX) NOT NULL,
	Solved BIT NOT NULL DEFAULT 0,
	[Deleted] BIT NOT NULL DEFAULT 0,
	[User] NVARCHAR(128) NOT NULL,
	CONSTRAINT PK_CustomError PRIMARY KEY CLUSTERED ([ID])
);

/*CLEAN UP*/
/*
USE JazzMetrics;
go

DROP TABLE [User];
DROP TABLE [Role];
DROP TABLE [Language];
DROP TABLE [CustomError];

USE [master];
go
DROP DATABASE JazzMetrics;
go
*/